export const GREETINGS = [
  "What's on your mind today?",
  "How can I help you today?",
  "What can I help with?",
  "How can I assist you today?",
  "What would you like to work on?",
  "What are you working on today?",
  "Ask me anything.",
  "How's it going? What can I help with?",
  "Need help with something?",
  "What would you like to do today?",
  "Ready when you are.",
  "What would you like to explore today?",
  "What can we work on together?",
  "What's your next project?",
  "How can I make your day easier?",
  "What are you curious about today?",
  "What would you like to create?",
  "Need a hand with something?",
  "What challenge are you tackling today?",
  "Where would you like to start?",
];
